version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_3_trab
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:1234@mysql:3306/series
    depends_on:
      - mysql
    command: sh -c "npx prisma migrate dev --name init --schema=./prisma/schema.prisma && npm run dev"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: series
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
